substitutions:
  name: ble-proxy-c6
  friendly_name: Bluetooth Proxy C6

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: seeed_xiao_esp32c6
  variant: ESP32C6
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Bluetooth Proxy C6 Fallback"
    password: !secret fallback_ap_password

captive_portal:

esp32_ble:
  max_connections: 5

esp32_ble_tracker:
  scan_parameters:
    interval: 300ms
    window: 300ms
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 5
